# docker-compose.yml
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
