# server/Dockerfile
FROM node:20-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code and build it
COPY . .
RUN npm run build

# Expose the port and start the server
EXPOSE 8080
CMD ["npm", "start"]
